// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm7_iZYdGNJPG1PzNqVofZyfKKy8yeDj0',
    appId: '1:695727196157:web:745723cdc3f90c5639bb94',
    messagingSenderId: '695727196157',
    projectId: 'typington-5921a',
    authDomain: 'typington-5921a.firebaseapp.com',
    storageBucket: 'typington-5921a.appspot.com',
    measurementId: 'G-Y69ZZNLKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHrgSs922LSw-sC5SKwg7X4FTRhBq_SSc',
    appId: '1:695727196157:android:28a2fbfdd26aec5439bb94',
    messagingSenderId: '695727196157',
    projectId: 'typington-5921a',
    storageBucket: 'typington-5921a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCttHdm9xd-N4nf-2unfXHvKkzfhOR4Jgw',
    appId: '1:695727196157:ios:52370e5cd378ae8639bb94',
    messagingSenderId: '695727196157',
    projectId: 'typington-5921a',
    storageBucket: 'typington-5921a.appspot.com',
    iosClientId: '695727196157-830o4le0p0arv0g7tl5nu32oqgqkc1bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.typingthon',
  );
}
